/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unoxtutti.gui;

import javax.swing.JOptionPane;
import unoxtutti.UnoXTutti;
import unoxtutti.domain.Player;

/**
 *
 * @author picardi
 */
public class AutenticarsiGUI extends javax.swing.JDialog {
	/**
	 * Creates new form AuthenticationDialog
	 */
	public AutenticarsiGUI(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.Box.Filler filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        emailSigninField = new javax.swing.JTextField();
        javax.swing.Box.Filler filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.Box.Filler filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        passSigninField = new javax.swing.JTextField();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        signinButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        nameSignupField = new javax.swing.JTextField();
        javax.swing.Box.Filler filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.Box.Filler filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        emailSignupField = new javax.swing.JTextField();
        javax.swing.Box.Filler filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.Box.Filler filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        passSignupField = new javax.swing.JTextField();
        javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
        signupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5))));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Email:");
        jPanel2.add(jLabel1);
        jPanel2.add(filler2);

        emailSigninField.setColumns(40);
        emailSigninField.setAlignmentX(0.0F);
        jPanel2.add(emailSigninField);
        jPanel2.add(filler3);

        jLabel2.setText("Password:");
        jPanel2.add(jLabel2);
        jPanel2.add(filler4);

        passSigninField.setColumns(15);
        passSigninField.setAlignmentX(0.0F);
        jPanel2.add(passSigninField);

        jPanel4.add(jPanel2, java.awt.BorderLayout.NORTH);

        signinButton.setText("Entra");
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });
        jPanel5.add(signinButton);

        jPanel4.add(jPanel5, java.awt.BorderLayout.SOUTH);

        tabbedPane.addTab("Accedi", jPanel4);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setText("Nome utente:");
        jPanel3.add(jLabel5);

        nameSignupField.setColumns(40);
        nameSignupField.setAlignmentX(0.0F);
        jPanel3.add(nameSignupField);
        jPanel3.add(filler9);

        jLabel3.setText("Email:");
        jPanel3.add(jLabel3);
        jPanel3.add(filler5);

        emailSignupField.setColumns(40);
        emailSignupField.setAlignmentX(0.0F);
        jPanel3.add(emailSignupField);
        jPanel3.add(filler6);

        jLabel4.setText("Password:");
        jPanel3.add(jLabel4);
        jPanel3.add(filler7);

        passSignupField.setColumns(15);
        passSignupField.setAlignmentX(0.0F);
        jPanel3.add(passSignupField);

        jPanel6.add(jPanel3, java.awt.BorderLayout.NORTH);

        signupButton.setText("Crea nuovo utente");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        jPanel7.add(signupButton);

        jPanel6.add(jPanel7, java.awt.BorderLayout.SOUTH);

        tabbedPane.addTab("Registrati", jPanel6);

        jPanel1.add(tabbedPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        String email = emailSigninField.getText().trim();
		String password = passSigninField.getText().trim();
		Player pl = UnoXTutti.theAutController.accedi(email, password);
		if (pl == null) JOptionPane.showMessageDialog(this, "Credenziali non valide. Impossibile accedere.");
		else setVisible(false);
    }//GEN-LAST:event_signinButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        String userName = nameSignupField.getText().trim();
		String email = emailSignupField.getText().trim();
		String password = passSignupField.getText().trim();
		boolean ok = UnoXTutti.theAutController.registra(userName, email, password);
		if (!ok) JOptionPane.showMessageDialog(this, "Impossibile creare untente con questi dati. Riprova.");
		else {
			JOptionPane.showMessageDialog(this, "Giocatore " + userName + " creato. Ora puoi accedere.");
			this.tabbedPane.setSelectedIndex(0);
		}
    }//GEN-LAST:event_signupButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AutenticarsiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AutenticarsiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AutenticarsiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AutenticarsiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				AutenticarsiGUI dialog = new AutenticarsiGUI(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailSigninField;
    private javax.swing.JTextField emailSignupField;
    private javax.swing.JTextField nameSignupField;
    private javax.swing.JTextField passSigninField;
    private javax.swing.JTextField passSignupField;
    private javax.swing.JButton signinButton;
    private javax.swing.JButton signupButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
