/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unoxtutti.gui;

import java.awt.Rectangle;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import unoxtutti.UnoXTutti;
import unoxtutti.domain.ServerGame;
import unoxtutti.domain.RemoteRoom;
import unoxtutti.domain.Player;
import unoxtutti.domain.RemotePartita;

/**
 * Questo pannello fornisce informazioni su una stanza e d&agrave; accesso alle
 * operazioni che l'utente pu&ograve; eseguire appena entrato in una stanza
 *
 * @author picardi
 */
public class InsideMatchPanel extends MainWindowSubPanel implements Observer {

    private RemoteRoom currentRoom;

    /**
     * Creates new form InsideRoomPanel
     */
    public InsideMatchPanel() {
        initComponents();
    }

    @Override
    public void initializeContent() {
        currentRoom = UnoXTutti.theUxtController.getCurrentRoom();
        
        this.playerstanza.setModel(currentRoom.getPartita().getAllPlayerOfMatch());
        currentRoom.getPartita().addObserver(this);
        //this.partiteList.setModel(currentRoom.getPartiteAsList());
        this.PartitaNameLabel.setText("Partita: " + currentRoom.getPartita().getNomePartita()+ " Modalità: "+currentRoom.getPartita().getModalita());
       // this.Entra.setEnabled(false);
       if(currentRoom.getPartita().getCodiceProprietario()==currentRoom.getConnectedPlayer().hashCode()){
       jButton3.setEnabled(true);
       }
      
      
       
       
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        javax.swing.JSplitPane jSplitPane1 = new javax.swing.JSplitPane();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        playerstanza = new javax.swing.JList<>();
        roomPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        PartitaNameLabel = new javax.swing.JLabel();
        partitaExitButton = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(150, 23));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 140));

        playerstanza.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        playerstanza.setMinimumSize(new java.awt.Dimension(150, 85));
        playerstanza.setPreferredSize(new java.awt.Dimension(150, 85));
        jScrollPane1.setViewportView(playerstanza);

        jSplitPane1.setLeftComponent(jScrollPane1);

        roomPanel.setPreferredSize(new java.awt.Dimension(100, 399));
        roomPanel.setLayout(new java.awt.BorderLayout());
        roomPanel.add(filler3, java.awt.BorderLayout.LINE_START);

        jPanel6.add(jPanel3);
        jPanel6.add(jPanel5);

        jButton3.setText("Gioca");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        roomPanel.add(jPanel6, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(roomPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout(5, 0));

        PartitaNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        PartitaNameLabel.setText("Partita:");
        jPanel2.add(PartitaNameLabel, java.awt.BorderLayout.CENTER);

        partitaExitButton.setText("Esci");
        partitaExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partitaExitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(partitaExitButton, java.awt.BorderLayout.LINE_END);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void partitaExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partitaExitButtonActionPerformed
        UnoXTutti.theUxtController.esciDaStanza();
        mainWindow.setGuiState(UnoXTuttiGUI.GUIState.OUTSIDE_ROOM);
    }//GEN-LAST:event_partitaExitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        UnoXTutti.theUxtController.startMatch(currentRoom.getPartita().getCode());
    }//GEN-LAST:event_PlayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PartitaNameLabel;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton partitaExitButton;
    private javax.swing.JList<Player> playerstanza;
    private javax.swing.JPanel roomPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        if(((RemotePartita)o).getEvento().equals("iniziomatch")){
             mainWindow.setGuiState(UnoXTuttiGUI.GUIState.MANCHE_ROOM);
             UnoXTutti.theUxtController.setGo(true);
             
        
        }
        
    }
}
