/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unoxtutti.gui;

import java.awt.Cursor;

/**
 * Una Dialog che mostra un messaggio e rimane in attesa che qualche
 * tipo di transizione sia completata.
 * @author picardi
 */
public class TransitionDialog extends javax.swing.JDialog {

	private Cursor swapCursor;
	/**
	 * Creates new form TransitionDialog
	 */
	public TransitionDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public void setMessage(String msg) {
		this.messagePane.setText(msg);
	}
	
	@Override
	public void setVisible(boolean visible) {
		super.setVisible(visible);
		if (visible) {
			swapCursor = this.getCursor();
			this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
		} else {
			this.setCursor(swapCursor);
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePane = new javax.swing.JTextPane();

        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setSize(new java.awt.Dimension(400, 300));

        messagePane.setEditable(false);
        messagePane.setBackground(new java.awt.Color(238, 238, 238));
        messagePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        getContentPane().add(messagePane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane messagePane;
    // End of variables declaration//GEN-END:variables
}
