/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unoxtutti.webserver;

import java.awt.event.WindowEvent;

/**
 *
 * @author picardi
 */
public class WebServerStopDialog extends javax.swing.JDialog {
	private WebServer webServer;
	/**
	 * Creates new form WebServerStopDialog
	 */
	public WebServerStopDialog(java.awt.Frame parent, WebServer ws) {
		super(parent, true);
		initComponents();
		webServer = ws;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stopButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        stopButton.setText("Stop Web Server");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopButton, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
		webServer.setStopSuggested(true);
		while (!webServer.isStopped());
		setVisible(false);
		dispatchEvent(new WindowEvent(
                    this, WindowEvent.WINDOW_CLOSING));		
    }//GEN-LAST:event_stopButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
