progetto: 
	gcc banditore.c -o banditore
	gcc agente.c -o agente
	gcc cliente.c -o cliente
	gcc generatore.c -o generatore

avvia: 
	generatore . ./cliente
        
avvia2:
	banditore Risorse_Banditore.ban
